---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_paths:
  - "coverage/"
  - "dist/"
ratings:
   paths:
   - "src/**/**.ts"
plugins:
  tslint:
    enabled: true
    config: tslint.json
